spring:
    application:
        name: vk.api
    datasource:
        url: jdbc:mariadb://localhost:3306/vk-api-db
        username: vk-api
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8080
api:
    jsonplaceholder:
        url: https://jsonplaceholder.typicode.com/api/