package com.ddrobunin.vk.api.security;

public enum Role {
    ADMIN,
    POSTS,
    USERS,
    ALBUMS,
    POSTS_VIEWER, USERS_VIEWER, ALBUMS_VIEWER,
    POSTS_CREATOR, USERS_CREATOR, ALBUMS_CREATOR,
    POSTS_UPDATER, USERS_UPDATER, ALBUMS_UPDATER,
    POSTS_DELETER, USERS_DELETER, ALBUMS_DELETER,
}
